# Generated by Django 3.1.7 on 2021-08-24 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip_title', models.CharField(max_length=254)),
                ('tip_body', models.TextField(blank=True, default='', null=True)),
                ('tip_by', models.CharField(default='', max_length=254)),
                ('tip_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-tip_date'],
            },
        ),
    ]
