# Generated by Django 3.1.7 on 2021-08-25 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tip',
            options={'ordering': ['-tip_title']},
        ),
        migrations.RemoveField(
            model_name='tip',
            name='tip_date',
        ),
    ]
